<?php

namespace jdgOpenCode\verifactu;

use jdgOpenCode\verifactu\Type;
use Soap\ExtSoapEngine\Configuration\ClassMap\ClassMapCollection;
use Soap\ExtSoapEngine\Configuration\ClassMap\ClassMap;

class AEATClassmap
{
    public static function getCollection() : \Soap\ExtSoapEngine\Configuration\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection(
            new ClassMap('CabeceraType', Type\CabeceraType::class),
            new ClassMap('RemisionVoluntaria', Type\RemisionVoluntaria::class),
            new ClassMap('RemisionRequerimiento', Type\RemisionRequerimiento::class),
            new ClassMap('DatosPresentacionType', Type\DatosPresentacionType::class),
            new ClassMap('DatosPresentacion2Type', Type\DatosPresentacion2Type::class),
            new ClassMap('PeriodoImputacionType', Type\PeriodoImputacionType::class),
            new ClassMap('IDFacturaExpedidaBCType', Type\IDFacturaExpedidaBCType::class),
            new ClassMap('IDFacturaExpedidaBajaType', Type\IDFacturaExpedidaBajaType::class),
            new ClassMap('RegistroFacturacionAltaType', Type\RegistroFacturacionAltaType::class),
            new ClassMap('FacturasRectificadas', Type\FacturasRectificadas::class),
            new ClassMap('FacturasSustituidas', Type\FacturasSustituidas::class),
            new ClassMap('Destinatarios', Type\Destinatarios::class),
            new ClassMap('Encadenamiento', Type\Encadenamiento::class),
            new ClassMap('RegistroFacturacionAnulacionType', Type\RegistroFacturacionAnulacionType::class),
            new ClassMap('EncadenamientoFacturaAnteriorType', Type\EncadenamientoFacturaAnteriorType::class),
            new ClassMap('SistemaInformaticoType', Type\SistemaInformaticoType::class),
            new ClassMap('IDFacturaExpedidaType', Type\IDFacturaExpedidaType::class),
            new ClassMap('IDFacturaARType', Type\IDFacturaARType::class),
            new ClassMap('DetalleType', Type\DetalleType::class),
            new ClassMap('DesgloseRectificacionType', Type\DesgloseRectificacionType::class),
            new ClassMap('PersonaFisicaJuridicaESType', Type\PersonaFisicaJuridicaESType::class),
            new ClassMap('PersonaFisicaJuridicaType', Type\PersonaFisicaJuridicaType::class),
            new ClassMap('IDOtroType', Type\IDOtroType::class),
            new ClassMap('RangoFechaExpedicionType', Type\RangoFechaExpedicionType::class),
            new ClassMap('FechaExpedicionConsultaType', Type\FechaExpedicionConsultaType::class),
            new ClassMap('RegistroDuplicadoType', Type\RegistroDuplicadoType::class),
            new ClassMap('DesgloseType', Type\DesgloseType::class),
            new ClassMap('ContraparteConsultaType', Type\ContraparteConsultaType::class),
            new ClassMap('CabeceraConsultaSf', Type\CabeceraConsultaSf::class),
            new ClassMap('ObligadoEmisionConsultaType', Type\ObligadoEmisionConsultaType::class),
            new ClassMap('ObligadoGeneracionType', Type\ObligadoGeneracionType::class),
            new ClassMap('OperacionType', Type\OperacionType::class),
            new ClassMap('RegistroAlta', Type\RegistroAlta::class),
            new ClassMap('RegistroAnulacion', Type\RegistroAnulacion::class),
            new ClassMap('SignatureType', Type\SignatureType::class),
            new ClassMap('SignatureValueType', Type\SignatureValueType::class),
            new ClassMap('SignedInfoType', Type\SignedInfoType::class),
            new ClassMap('CanonicalizationMethodType', Type\CanonicalizationMethodType::class),
            new ClassMap('SignatureMethodType', Type\SignatureMethodType::class),
            new ClassMap('ReferenceType', Type\ReferenceType::class),
            new ClassMap('TransformsType', Type\TransformsType::class),
            new ClassMap('TransformType', Type\TransformType::class),
            new ClassMap('DigestMethodType', Type\DigestMethodType::class),
            new ClassMap('KeyInfoType', Type\KeyInfoType::class),
            new ClassMap('KeyValueType', Type\KeyValueType::class),
            new ClassMap('RetrievalMethodType', Type\RetrievalMethodType::class),
            new ClassMap('X509DataType', Type\X509DataType::class),
            new ClassMap('X509IssuerSerialType', Type\X509IssuerSerialType::class),
            new ClassMap('PGPDataType', Type\PGPDataType::class),
            new ClassMap('SPKIDataType', Type\SPKIDataType::class),
            new ClassMap('ObjectType', Type\ObjectType::class),
            new ClassMap('ManifestType', Type\ManifestType::class),
            new ClassMap('SignaturePropertiesType', Type\SignaturePropertiesType::class),
            new ClassMap('SignaturePropertyType', Type\SignaturePropertyType::class),
            new ClassMap('DSAKeyValueType', Type\DSAKeyValueType::class),
            new ClassMap('RSAKeyValueType', Type\RSAKeyValueType::class),
            new ClassMap('Signature', Type\Signature::class),
            new ClassMap('SignatureValue', Type\SignatureValue::class),
            new ClassMap('SignedInfo', Type\SignedInfo::class),
            new ClassMap('CanonicalizationMethod', Type\CanonicalizationMethod::class),
            new ClassMap('SignatureMethod', Type\SignatureMethod::class),
            new ClassMap('Reference', Type\Reference::class),
            new ClassMap('Transforms', Type\Transforms::class),
            new ClassMap('Transform', Type\Transform::class),
            new ClassMap('DigestMethod', Type\DigestMethod::class),
            new ClassMap('KeyInfo', Type\KeyInfo::class),
            new ClassMap('KeyValue', Type\KeyValue::class),
            new ClassMap('RetrievalMethod', Type\RetrievalMethod::class),
            new ClassMap('X509Data', Type\X509Data::class),
            new ClassMap('PGPData', Type\PGPData::class),
            new ClassMap('SPKIData', Type\SPKIData::class),
            new ClassMap('Manifest', Type\Manifest::class),
            new ClassMap('SignatureProperties', Type\SignatureProperties::class),
            new ClassMap('SignatureProperty', Type\SignatureProperty::class),
            new ClassMap('DSAKeyValue', Type\DSAKeyValue::class),
            new ClassMap('RSAKeyValue', Type\RSAKeyValue::class),
            new ClassMap('RegistroFacturaType', Type\RegistroFacturaType::class),
            new ClassMap('RegFactuSistemaFacturacion', Type\RegFactuSistemaFacturacion::class),
            new ClassMap('ConsultaFactuSistemaFacturacionType', Type\ConsultaFactuSistemaFacturacionType::class),
            new ClassMap('LRFiltroRegFacturacionType', Type\LRFiltroRegFacturacionType::class),
            new ClassMap('DatosAdicionalesRespuestaType', Type\DatosAdicionalesRespuestaType::class),
            new ClassMap('ConsultaFactuSistemaFacturacion', Type\ConsultaFactuSistemaFacturacion::class),
            new ClassMap('RespuestaConsultaFactuSistemaFacturacionType', Type\RespuestaConsultaFactuSistemaFacturacionType::class),
            new ClassMap('EstadoRegFactuType', Type\EstadoRegFactuType::class),
            new ClassMap('RegistroRespuestaConsultaRegFacturacionType', Type\RegistroRespuestaConsultaRegFacturacionType::class),
            new ClassMap('RespuestaConsultaType', Type\RespuestaConsultaType::class),
            new ClassMap('PeriodoImputacion', Type\PeriodoImputacion::class),
            new ClassMap('RespuestaDatosRegistroFacturacionType', Type\RespuestaDatosRegistroFacturacionType::class),
            new ClassMap('RespuestaConsultaFactuSistemaFacturacion', Type\RespuestaConsultaFactuSistemaFacturacion::class),
            new ClassMap('RespuestaBaseType', Type\RespuestaBaseType::class),
            new ClassMap('RespuestaRegFactuSistemaFacturacionType', Type\RespuestaRegFactuSistemaFacturacionType::class),
            new ClassMap('RespuestaExpedidaType', Type\RespuestaExpedidaType::class),
            new ClassMap('RespuestaRegFactuSistemaFacturacion', Type\RespuestaRegFactuSistemaFacturacion::class),
        );
    }
}

